### PR TITLE
Clean up automatic release to unified-auctions.makerdao.com

### PR DESCRIPTION
**Pull request by BracketJohn**
Contributes to https://github.com/sidestream-tech/auction-ui/issues/287

### CODE REVIEW

**Comment by BracketJohn** [comment]
When doing release v0.9.1 to test availability of the domain https://unified-auctions.makerdao.com, we ended up in an eternal TLS redirect when we have "partial" TLS termination in our cluster where we tried to terminate https://production.auction-ui.k8s.sidestream.tech in our cluster and https://unified-auctions.makerdao.com outside of our cluster (in the cloudflare makerdao account).

So I've now removed the https://production.auction-ui.k8s.sidestream.tech deployment and the belonging TLS cert generation + termination. I think that this is OK as this was only a bridge to the time when the domain would be made available to us.

Currently, the following secrets are used:
- frontend (at build time):
    ```yaml
        - key: PRODUCTION_DOMAIN
          value_from_secret: auction-ui/auctions.makerdao.network/frontend/production_domain
        - key: INFURA_PROJECT_ID
          value_from_secret: auction-ui/auctions.makerdao.network/frontend/infura_project_id
        - key: CONTACT_EMAIL
          value_from_secret: auction-ui/auctions.makerdao.network/frontend/contact_email
        - key: DEFAULT_ETHEREUM_NETWORK
          value_from_secret: auction-ui/main.auction-ui.k8s.sidestream.tech/frontend/default_etherum_network
    ```
- twitter bot (at runtime):
    ```yaml
  secretChamberPath: "auction-ui/production.auction-ui.k8s.sidestream.tech/bot-twitter"
    ```


So in total we mix the following environments:
- frontend: auction-ui/auctions.makerdao.network
- frontend: auction-ui/main.auction-ui.k8s.sidestream.tech
- twitter bot: auction-ui/production.auction-ui.k8s.sidestream.tech

Following up to the discussion we had, do you want to change any of the above @valiafetisov?

**Comment by valiafetisov** [comment]
> Currently, the following secrets are used:

I suggest to use `production` secrets, since they are already exists and seems to be correct

```yaml
    - key: PRODUCTION_DOMAIN
      value_from_secret: auction-ui/production.auction-ui.k8s.sidestream.tech/frontend/production_domain
    - key: INFURA_PROJECT_ID
      value_from_secret: auction-ui/production.auction-ui.k8s.sidestream.tech/frontend/infura_project_id
    - key: CONTACT_EMAIL
      value_from_secret: auction-ui/production.auction-ui.k8s.sidestream.tech/frontend/contact_email
    - key: DEFAULT_ETHEREUM_NETWORK
      value_from_secret: auction-ui/production.auction-ui.k8s.sidestream.tech/frontend/default_etherum_network
```
```yaml
secretChamberPath: "auction-ui/production.auction-ui.k8s.sidestream.tech/bot-twitter"
```

> I think that this is OK as this was only a bridge to the time when the domain would be made available to us.

I think it would make sense if `http[s]://production.auction-ui.k8s.sidestream.tech` would redirect to `https://unified-auctions.makerdao.com` the same way `http[s]://auctions.makerdao.network` will need to redirect to `https://unified-auctions.makerdao.com` in the future. Maybe you can use `production.` domain to test it out? Or do you say that `production.` and `auctions.` are differently terminated, therefore this wouldn't make sense as a testing strategy?

**Comment by BracketJohn** [comment]
I've updated the image build to use the `production.` secrets only, the twitter bot already used `production.`.

> Or do you say that production. and auctions. are differently terminated, therefore this wouldn't make sense as a testing strategy?

yeah, it would not make much sense. `http[s]://production.auction-ui.k8s.sidestream.tech` is terminated with a TLS Cert we generate automatically inside our cluster. The termination of `https://unified-auctions.makerdao.com` happens in Cloudflare.

If we want to have a redirect like that, we have to add that to our cloudflare rule set to catch the traffic before it is matched onto our k8s cluster via the other rule we have there: `*.k8s.sidestream.tech -> aws-eks-cluster`. I think we don't need to redirect or offer `production.`, as it was never publicly used / promoted, right? I know it would be nice to have, but it is quite hacky to create rules like:
```
*.k8s.sidestream.tech -> aws-eks-cluster
production.auction-ui.k8s.sidestream.tech -> unified-auctons.makerdao.com
```
and hope for right order of execution.

As for `http[s]://auctions.makerdao.network`, maker should be able to easily add that redirect to their top level DNS rules the same as they did for unified-auctions.makerdao.com.

**Comment by valiafetisov** [comment]
>  I think we don't need to redirect or offer `production.`, as it was never publicly used / promoted, right?

Correct

> maker should be able to easily add that redirect to their top level DNS rules the same as they did for unified-auctions.makerdao.com.

What kind of record should they add? (to _redirect_, not serve the same deployment under a different domain) Or do you mean that they should add the same `CNAME` record and we would redirect it on the ingress level?

**Comment by BracketJohn** [comment]
> Correct, it was never published (to my knowledge) and we don't need to support it in general. Then, let's delete this domain!

alright, it's already going to be deleted properly on the next release, right now due to my debugging it already fails to resolve though as I've removed the TLS termination.

> What kind of record should they add? (to redirect, not serve the same deployment under a different domain) Or do you mean that they should add the same CNAME record and we would redirect it on the ingress level?

They should configure the redirect. As cloudflare  is used, I'd recommend creating a page rule for a 301 redirect following this nice tutorial: https://developers.cloudflare.com/pages/how-to/www-redirect/

Should I relay that to @LukSteib or will you take that with you? 

Good for pointing it out, I did not think about validity of the old deployment (:

**Comment by valiafetisov** [comment]
> Should I relay that to @LukSteib or will you take that with you?

Yes, please.

**Comment by LukSteib** [comment]
> They should configure the redirect. As cloudflare is used, I'd recommend creating a page rule for a 301 permanent redirect following this nice tutorial: https://developers.cloudflare.com/pages/how-to/www-redirect/. This will also lead to search engines, ... updating their references.

I will take that on my agenda. But based on the experience we have made in the past, this process can take some time and won't be done immediately. As this refers to the old domain again there is another set of contact persons I have to reach out to. So for the time being I would highly vouch to have both domains running in parallel.

**Comment by BracketJohn** [comment]
Alright!

Then lets:
- merge this PR so that:
  - `unified-auctions.` starts to be continuously deployed
  - `production.` stops being deployed and available
- you take onto your list that they at some point put in the redirect
- @deusavalon and I manually deploy https://auctions.makerdao.network/ until the redirect is setup

Deal?

**Comment by LukSteib** [comment]
> Deal?

Deal! 

> unified-auctions. starts to be continuously deployed

Just to get the sequence right. I have already published the release images for the upcoming release. Does this affect the contiouse deployment here?

**Comment by BracketJohn** [comment]
> Just to get the sequence right. I have already published the release images for the upcoming release. Does this affect the contiouse deployment here?

yes :( We can re-run the release though (or increase the minor version by 1)

**Review by LukSteib — APPROVED** [review]

**Pull request merged**
