### PR TITLE
Allowance amount logic

### PR DESCRIPTION
**Pull request by valiafetisov**
Closes https://github.com/sidestream-tech/unified-auctions-ui/issues/123

Functional testing can be done by executing in the js console:

1. To fetch amount that contract can withdraw from the user wallet:
    ```js
    await $nuxt.$store.dispatch('authorizations/fetchAllowanceAmount'); $nuxt.$store.getters['authorizations/allowanceAmount'].toFixed()
    ```

2. To set limited allowance amount
    ```js
    await $nuxt.$store.dispatch('authorizations/setAllowanceAmount', '100');
    ```
    - then rerun `1` to validate new allowance

3. Can be checked checked together with deposit logic (implemented in https://github.com/sidestream-tech/unified-auctions-ui/pull/143)
    ```js
    $nuxt.$store.dispatch('wallet/depositToVAT', '90')
    ```
    - then rerun `1` to validate that allowance decreased by 90

4. To set "unlimited" amount
    ```js
    await $nuxt.$store.dispatch('authorizations/setAllowanceAmount'); 
    ```
    - then rerun `1` to validate new allowance

5. To remove allowance
    ```js
    await $nuxt.$store.dispatch('authorizations/setAllowanceAmount', '0'); 
    ```

### CODE REVIEW

**Review by LukSteib — CHANGES_REQUESTED** [review]
All tests executed on `goerli` 
Testing with a wallet that had unlimited allowance from past:
- [x] Step to set allowance to `unlimited` amount throws error (see console log [1] below)

Testing with new wallet that had no allowance set yet
- [ ] fetching current allowance returns 2 errors (see console log [2] below)
- [x] trying to set the allowance to a specific value returns error (see console log [3] below)


[1]
```
Setting allowance amount error: invalid BigNumber value (argument="value", value="1.15792089237316195423570985008687907853269984665640564039457584007913129639935e+77", code=INVALID_ARGUMENT, version=bignumber/5.5.0)
```
[2]
```
Fetching allowance amount error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')
```
[3]
```
Setting allowance amount error: No signer has been created for the "goerli" network
```

**Review by benediktkaiser — APPROVED** [review]
The code looks good to me. However I wanted to ask in which PR you wanted to take care of the `walletLastUpdatedDate` values. (first mentioned in #138)

**Comment by valiafetisov** [comment]
> Setting allowance amount error: invalid BigNumber value

It seems like you're testing outdated code, before fd75277 was pushed. Can you please pull latest changes and try again?

> No signer has been created for the "goerli" network

This sometimes happens on the dev after the hot reload. Not a production bug. General rule: do full nuxt restart and page refresh after pulling changes / switching branches.

**Comment by valiafetisov** [comment]
> However I wanted to ask in which PR you wanted to take care of the walletLastUpdatedDate values. (first mentioned in https://github.com/sidestream-tech/unified-auctions-ui/pull/138)

I thought you can take care of it in https://github.com/sidestream-tech/unified-auctions-ui/issues/136 since you anyway would need to slightly modify store (by adding getters for example). I can also add it in a separate PR if you wish.

**Comment by LukSteib** [comment]
> It seems like you're testing outdated code, before https://github.com/sidestream-tech/unified-auctions-ui/commit/fd7527703ec00725642531610afa223cd61e0b5f was pushed. Can you please pull latest changes and try again?

If have pulled latest changes but still experiencing all of the issues described [here](https://github.com/sidestream-tech/unified-auctions-ui/pull/144#pullrequestreview-911256243)

**Comment by valiafetisov** [comment]
> Step to set allowance to unlimited amount throws error

Sorry, my bad, was able to reproduce and fix.

> Uncaught TypeError: Cannot read properties of undefined (reading 'toFixed')

Source for this error is the testing command itself. Updated the first command in the instruction https://github.com/sidestream-tech/unified-auctions-ui/pull/144#issue-1169910469

Other errors: couldn't reproduce. Even running on the mainnet fetching returns 0 without errors. I believe those two other errors caused by hot reload.

**Review by LukSteib — APPROVED** [review]
> Other errors: couldn't reproduce. Even running on the mainnet fetching returns 0 without errors. I believe those two other errors caused by hot reload.

My bad, tested with another browser session and a new wallet (simply forgot to connect wallet :( ). Hence the errors shown above. So everything fine and even the error message saying that "no address" found makes complete sense.

**Pull request merged**
