### PR TITLE
Callee refactoring

### PR DESCRIPTION
**Pull request by valiafetisov**
Partially addresses #73 

In this PR all logic related to callees and uniswap was rearranged and splitted into different files. Now every callee is required (enforced by the type) to have two functions: one for calculating the price of the collateral, the other is for producing the parameters for the transaction. Therefore, both things should be tested again for each of two callees that we support

### CODE REVIEW

**Review by benediktkaiser — DISMISSED** [review]
I had a flyover of the code. It all looks very clean to me. I like the approach you took to add different kinds of callee contracts. Should make collateral onboarding a lot easier!

I did not do a functional review.

**Comment by LukSteib** [comment]
@valiafetisov can you merge `main` with the vuex fix into this branch pls

**Review by LukSteib — COMMENTED** [review]
Successfully tested UniswapV2Callee on kovan:
https://kovan.etherscan.io/tx/0xda3cbb4037772da1e1d2a2c6dfc88190fcee3cc7d7f66b0f40d07a02f7b6d247

Still pending:
Test UniswapV2LpTokenCallee - might take some time due to necessity of:
* vault creation
* vault liquidation
* auction participation

**Review by LukSteib — CHANGES_REQUESTED** [review]
- [x] For the UniV2 LP-tokens we are not able to determine the price which hinders execution. Problem exists on both kovan [1] and mainnet [2]. On `kovan` we should be able to determine the price for `UNIV2DAIETH-A` at least. On `mainnet`we shoud be able to determine prices for all of them 

[1]
image

[2]
image

**Comment by valiafetisov** [comment]
Thanks for spotting it, I've imported the same file twice 😅. It works now, but I haven't checked if the displayed price is correct.

Screenshot 2022-02-04 at 16 18 47

**Review by LukSteib — APPROVED** [review]
Successfully executed a UniswapV2LpTokenCallee based tx on kovan: 

https://kovan.etherscan.io/tx/0xa35eb352b028c25a5719d411b1280cf13b84029b11645d12452885818369f316

**Pull request merged**
