### PR TITLE
Heap.io Integration

### LINKED ISSUE #238: Implement more granular analytics
**Goal:**
Gain better understanding of user behavior to improve overall service

**Context:**
We decided to get a better understanding of actual user behavior on our UI with the help of [heap.io](https://heap.io/). 
Decision for this service was made due to having used it in the past already and leverage the reference implementation.
Reference implementation can be found here: https://github.com/sidestream-tech/knowledge-cloud/pull/102

**Tasks:**
- [x] Implement heap.io support based on reference implementation (and documentation linked in assets section)
   - [x] as heap provides production and environment IDs check whether we are able to distinguish tracking for staging (https://main.auction-ui.k8s.sidestream.tech/collateral/?network=mainnet) and prod (https://unified-auctions.makerdao.com/)
- [x] Update readme referencing the correct env variables
- [ ] Check with @LukSteib if tracking works properly

**Assets:**
* Heap credentials can be found in bitwarden under "Heap Analytics Auction UI"
* Official heap documentation: https://developers.heap.io/docs/web

### PR DESCRIPTION
**Pull request by fegbert**
closes #238 

Please remember to run
```bash
secret export auction-ui/localhost/frontend --format dotenv > ./frontend/.env
```
before testing. Without it, the Heap.io Project ID will be missing!

Also, if you run into the `net::ERR_BLOCKED_BY_CLIENT` error, try disabling your adblocker

@valiafetisov (or someone from devops) still needs to set the IDs for the production and staging environments 🙂 
Variable name is `HEAPIO_ID`

### CODE REVIEW

**Review by valiafetisov — APPROVED** [review]

**Review by LukSteib — APPROVED** [review]
Approved from my side as well
* Was able to start locally and track events in heap dashboard

Once this PR is merged I will check whether tracking works for the staging environment as well. As outlined in the initial comment pls create necessary env variables for staging and production as part of this PR (probably @valiafetisov)

**Comment by valiafetisov** [comment]
> pls create necessary env variables for staging and production as part of this PR 

Are we going to use the same `HEAPIO_ID` for all environments including `localhost`? Ie, can you filter incoming stats by the origin?

**Comment by LukSteib** [comment]
> Are we going to use the same HEAPIO_ID for all environments including localhost?

Although I could filter by origin, I would prefer to use dedicated `HEAPIO_IDs` per environment. This makes overall tracking and dashboard usage much cleaner. 
You can find the respective IDs in bitwarden -> "Heap Analytics Auction UI"

**Comment by valiafetisov** [comment]
Executed commands (since `HEAPIO_ID` is actually exposed to frontend is not a real secret):
```
secret write auction-ui/localhost/frontend HEAPIO_ID 3872694786
secret write auction-ui/main.auction-ui.k8s.sidestream.tech/frontend HEAPIO_ID 1196782886
secret write auction-ui/production.auction-ui.k8s.sidestream.tech/frontend HEAPIO_ID 1482322679
secret write auction-ui/unified-auctions.makerdao.com/frontend HEAPIO_ID 1482322679
```

**Pull request merged**
