### PR TITLE
Vault liquidation by address

### PR DESCRIPTION
**Pull request by valiafetisov**
Adds possibility to liquidate vault by it's address, also updates wording and links on the `/vaults` page.

The data about the vault is fetched
Screenshot 2024-11-20 at 17 09 07

Vault liquidation transaction page
Screenshot 2024-11-20 at 17 24 12

Vault liquidation after successful liquidation
Screenshot 2024-11-20 at 17 25 09

### CODE REVIEW

**Comment by valiafetisov** [comment]
To functionally review/test this adjustment, `cd core` → `npm run simulate` → `Create collateral auction` → choose any of the active collaterals → `Create underwater vault` → note down address of the created vault. Then, keep running the simulation, switch to the frontend and use created vault address on the http://localhost:3000/vaults page.

**Review by LukSteib — CHANGES_REQUESTED** [review]
- Was able to liquidate `ETA-A` vault successfully
- [ ]  After first successful vault liquidation constantly getting an error on liquidation (see e1 for error in console) (even after re-starting whole setup and clearing nonce) 
- [ ] Unable to create an `LSE-MKR-A` vault via simulation on this PR (see e2 for error in terminal)


e1
```
MetaMask - RPC Error: Invalid transaction envelope type: specified type "0x2" but included a gasPrice instead of maxFeePerGas and maxPriorityFeePerGas
```


e2
```
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"Error: Transaction reverted without a reason string","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f02"},"to":"0x65C79fcB50Ca1594B025960e539eD7A9a6D434A3","data":"0x1504460f4c53452d4d4b522d410000000000000000000000000000000000000000000000","type":2,"accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32603,\"message\":\"Error: Transaction reverted without a reason string\",\"data\":{\"message\":\"Error: Transaction reverted without a reason string\",\"data\":\"0x\"}}}","error":{"code":-32603,"data":{"message":"Error: Transaction reverted without a reason string","data":"0x"}},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x59682f02\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266\",\"to\":\"0x65c79fcb50ca1594b025960e539ed7a9a6d434a3\",\"data\":\"0x1504460f4c53452d4d4b522d410000000000000000000000000000000000000000000000\"}],\"id\":44,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://127.0.0.1:8545"}}, tx={"data":"0x1504460f4c53452d4d4b522d410000000000000000000000000000000000000000000000","to":{},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f02"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","type":2,"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.6.2)
    at Logger.makeError (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at /Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 7)
ERROR: "hardhat:simulations" exited with 1.
```

**Comment by valiafetisov** [comment]
> After first successful vault liquidation constantly getting an error on liquidation (see e1 for error in console) (even after re-starting whole setup and clearing nonce)
> ```
> MetaMask - RPC Error: Invalid transaction envelope type: specified type "0x2" but included a gasPrice instead of maxFeePerGas and maxPriorityFeePerGas
> ```

Never had this error, and no gas-related changes were made in this PR. Double checked that simulation + liquidation + auction participation works both for `ETH-A` and `LSE-MKR-A` using UI.

> Error: cannot estimate gas; transaction may fail or may require manual gas limit

Based on the `to` and `data` found in the stack trace, failed transaction is `MCD_SPOT.poke('LSE-MKR-A')` call, which is permissionless and therefore I doubt has anything to do with the code in this PR, but general problems with the setup / rpc.


To potentially fix your setup you can try:
- Using a different REMOTE_RPC_URL (I lately had problems with alchemy)
- Running `npx hardhat clean` inside the `core` before you run `npm run simulate`

**Review by LukSteib — APPROVED** [review]
> Using a different REMOTE_RPC_URL (I lately had problems with alchemy)

Using a newly created `REMOTE_RPC_URL` resolved problems reported above. Was able to:
- liquidate `ETH-A` vault ✔️ 
- liquidate `LSE-MKR-A` vault ✔️

**Pull request merged**
