### PR TITLE
Improve simulations

### PR DESCRIPTION
**Pull request by valiafetisov**
This PR improves collateral auction simulations and keeper logging

### CODE REVIEW

**Comment by smilingspinach** [comment]
@LukSteib ping in here as well (coming from this [Thread](https://bienen-tech.slack.com/archives/C0260PX88AD/p1711038865085229))

**Comment by valiafetisov** [comment]
### Functional testing

1. Create necessary `.env` files
    - `secret export --format=dotenv auction-ui/localhost/core > core/.env` to create `core/.env`
    - Manually open/create `frontend/.env` and set the only variable `RPC_URL="http://127.0.0.1:8545"`
2. Start simulation
    - Check that you have appropriate node version with `node --version` (we use `16.9.1` in the CI) and change it if needed with `nvm`
    - Start simulation with `(cd core && npm i && npm run simulate)`
    - Choose `Create collateral auction` enter -> `Block number to fork from` enter -> `Select the collateral type` (select one of the live, eg `ETH-A`) -> `Create underwater vault` enter -> `Liquidate the vault` enter -> `Skip time` enter
3. Start frontend in another tab
    - `(cd frontend && npm i && npm run dev)`
    - Navigate to http://localhost:3000/collateral

**Comment by LukSteib** [comment]
Getting an error when trying to run collateral auction simulation. Any pointers on how to fix? 

```
✔ Select Simulation › Create collateral auction

/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/logger/src.ts/index.ts:261
        const error: any = new Error(message);
                           ^
Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.8)
    at Logger.makeError (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at EthersProviderWrapper.<anonymous> (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:444:23)
    at step (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/lukassteib/Github/unified-auctions-ui/core/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERROR: "hardhat:simulations" exited with 1.
```

**Comment by valiafetisov** [comment]
> Any pointers on how to fix?

The underlying reason is that hardhat _not yet started_ under the hood to accept RPC commands. As they [start as two different processes](https://github.com/sidestream-tech/unified-auctions-ui/blob/037502d467e62b49d7e58af11833240a1cd8e093/core/package.json#L15) it's hard to make a reliable fix. Most likely you just need to wait for a few seconds before choosing "Create collateral auction".  Could you please try that?

**Review by LukSteib — APPROVED** [review]
> Most likely you just need to wait for a few seconds before choosing "Create collateral auction". Could you please try that?

Worked, thanks for proposal and explanation

---
Review notes: 

- `ETH-A` auction ✅
   - able execute swap after 3 gradual time warps

<details>
  <summary>Simulation logs</summary>

Initial warp of 0.07692307692307693 of an auction time: 553 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
No active auctions are found, exiting the "evm_mine" loop

</details>


- `WBTC-A` auction ✅
   - able execute swap after 3 gradual time warps

<details>
  <summary>Simulation logs</summary>

Initial warp of 0.07692307692307693 of an auction time: 553 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
No active auctions are found, exiting the "evm_mine" loop

</details>

- `WSTETH-A` auction ✅
   - able execute swap after 16 gradual time warps

<details>
  <summary>Simulation logs</summary>

Initial warp of 0.07692307692307693 of an auction time: 553 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
Gradually skipping time, one block every 30 seconds
No active auctions are found, exiting the "evm_mine" loop
Step "Skip time" is successfully completed

</details>

**Pull request merged**
