### PR TITLE
Removed notification service

### PR DESCRIPTION
**Pull request by zoey-kaiser**
Contributes to #536
Closes https://github.com/sidestream-tech/unified-auctions-ui/issues/245

Checklist:
- [X] issue number linked above after pound (`#`)
    - replace "Closes " with "Contributes to" or other if this PR does not close the issue
- [X] issue checkboxes are all addressed
- [X] manually checked my feature / not applicable
- [X] wrote tests / not applicable
- [X] attached screenshots / not applicable

### CODE REVIEW

**Comment by zoey-kaiser** [comment]
To ensure we don't lose to existing code I moved the `notification-service` to a repository here: 

https://github.com/zoey-kaiser/notification-service

**Comment by valiafetisov** [comment]
- [ ] The new repo is missing licence file, which I believe obligatory
- [ ] I would also explain and link the original repo `sidestream-tech/unified-auctions-ui` in the readme
- [ ] I don't think it's the intended result to move `notification-service` to your private repo, although I don't feel to be the right person to comment on it. I expected that it should still belong to @sidestream-tech, but might be archived immediately since we don't plan to support it as of now, but still want to preserve the work. I guess, if you want to, you can fork it from there. But as I am not sure, I would pull @BracketJohn to resolve this question 🙂 

A little context for @BracketJohn: we're cleaning up the repository from unused or unrelated code as outlined in #536 and one of the proposals was to move `notification-service` into another repository. Maybe you have a another suggestion than outlined above?

**Comment by BracketJohn** [comment]
>  But as I am not sure, I would pull @BracketJohn to resolve this question 🙂

Yeah, let's please not move the code out of the sidestream-org,  instead:
1. commit 1: make an exact copy of the auctions ui and push it into a new repo `notification-service` (you could also do this by adding the new, empty repo as a new origin, that would preserve history but I don't think that that has any implications)
2. commit 2 (can be done via squashed PR to allow reviews):  remove everything besides the notification service + relevant meta-docs (license, readme, ....) you may want to keep in one move commit (still no alterations!)
4. do any alterations you may wish to do, e.g., by adding a fat disclaimer at the top of the readme with an explanation of the situation (eg see https://github.com/sidebase/sidebase-libs)
5. archieve the repo
6. delete the code in this repo, reference the moved location at least in the issue / PR, but maybe also somewhere in the readme (like: Archieved Services: notification-service, moved unaltered with same licensed status to: URL)

This should ensure the integrity of licensing, originality, ... much better than the current approach. Ensuring this integrity is important to make sure that the code stays in the public domain _clearly_, i.e., people should have a look at the notification-service and feel comfortable using it. This would not be the case with your current copy of the repo, as the License is missing. And even if you add a license now: From when does it apply? There's bigger disputes in the OS-community about sudden license changes with unclear implications.

Let me know if the above is too dense or if you disagree

**Comment by zoey-kaiser** [comment]
I create a new repository and moved the code there. Afterwards I added a disclaimer and and archived the repository.

The license was never changed and I added links back to the "real" unified-auctions-ui.

You can find the new repository here: https://github.com/sidestream-tech/notification-service

I think we can now go ahead with the removal of the notification-service in this PR!

**Review by valiafetisov — APPROVED** [review]

**Pull request merged**
